development:
  adapter: postgresql
  encoding: utf8
  database: coffeeshopper
  pool: 5
  username: jfp3
  password: admin

# test:
#   adapter: postgresql
#   encoding: utf8
#   database: coffeeshopper
#   pool: 5
#   username: jfp3
#   password: admin

production:
  adapter: postgresql
  encoding: utf8
  database: coffeeshopper
  username: jfp3
  password: admin
  pool: 5
  timeout: 5000
